version: '3'
services:

  # MS SQL Server
  # Borrowed from: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15
  # ====================================
  sqlserver:
    image: "mcr.microsoft.com/mssql/rhel/server"
    env_file:
      - .env.database # configure with env variables    
    ports:
      - "1400:1433"
    volumes:
      - database-data-mssql:/var/opt/mssql
      - ./shared:/shared

volumes:
  database-data-mssql: # named volumes can be managed easier using docker-compose
